### ISSUE TITLE
Squadron - No squadron found (1.16.5 Movecraft Alpha 3)

### ISSUE THREAD

**Issue by MysteryTimeTrav** [HalfQuark/SquadronsReloaded#4]
Paste bin of the issue in logs: https://pastebin.com/pvQs1Lji
![2021-06-26_22 55 20](https://user-images.githubusercontent.com/78791482/123532413-7fc49d00-d6d2-11eb-869e-ce9f564f12bc.png)

Description of issue: Piloting the carrier and then left-clicking the airskiff signs on the aircraft sends a null pilot contact. The aircraft cannot be controlled or given commands as it says no squadrons found but appears on the squadron list. They also sink when the carrier moves.

**Comment by HalfQuark** [comment]
Please test this again in the new version.
